version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
  api:
    build:
      context: api
      dockerfile: Dockerfile.dev
    restart: always
    command:
      [
        'sh',
        '-c',
        "prisma generate && python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
      ]
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/code
    depends_on:
      - db